[General]
# 不能用中文，否则会导致配置文件解析失败，程序无法启动
# 向用户显示的标题
title = ChuanQu Client
# 主题选项： system、light、dark
theme = dark
# 程序的 Icon
icon = vdiicon.ico
# 所有窗口上显示的 Logo
logo = vdiclient.png
# 启用 Kiosk 模式，用户无法关闭任何窗口
kiosk = False
# 启用/禁用全屏模式（在 Kiosk 模式下不适用）
fullscreen = True

#kiosk mode：kiosk 模式（自助终端 / 锁定模式），是一种将软件全屏运行、隐藏窗口边框 / 标题栏 / 关闭按钮，禁止用户退出或切换程序的模式，常用于瘦客户机、自助终端。
#viewer_kiosk = False

# 在打开 virt-viewer 之前，显示 / 导出 SPICE 配置文件（ini）
inidebug = True
# 选择要显示的客户机类型。可接受的值：both、lxc（纯命令行）、qemu
guest_type = both

# 显示虚拟机重启按钮
#show_reset = True
# 设置窗口尺寸。如果窗口大小不正确，请仅使用此选项
#window_width = 800
#window_height = 600
# 虚拟机列表分页数量
#page_size = 10
# 无操作自动退出超时（分钟，0=不超时）
#timeout = 15


#PVE-VDIClient 支持多集群配置。
#配置集群的格式规则：以 Hosts. 开头，后面跟上你想展示给终端用户看的集群名称。
#示例：Hosts.PVE，最终软件界面上就会显示「PVE」这个集群名称。

[Hosts.PVE]
# 集群内服务器的 JSON 格式字典
# 格式：'IP地址或域名': 端口号
# 注意：确保所有行都缩进对齐
hostpool = {
               "192.168.1.100" : 8006,
               "192.168.1.101" : 8006,
               "192.168.1.102" : 8006
           }       
# This is the authentication backend that will be used to authenticate
#认证方式（pve / pam / ldap）
auth_backend = pve
# 是否启用二次验证 TOTP
auth_totp = false
# 是否校验 SSL 证书（内网环境建议关闭）
tls_verify = false
# User name (if using token)
# NOTE: If only one cluster is defined, this will auto-login
# If user, token_name, and token_value are set
#user = user
# API Token Name
#token_name = dvi
# API Token Value
#token_value = xxx-x-x-x-xxx
# Password Reset Command Launch. Has to be full executable Command
#pwresetcmd = start chrome --app=http://pwreset.example.com
# Automatically connect to a VMID upon authentication
#auto_vmid = 100
[Hosts.S1]
hostpool = {"192.168.5.102":8006}    
auth_backend = pve
tls_verify = false

# An additional cluster definition
#[Hosts.PVE2]
# JSON dictionary of servers in the cluster
# Format is 'IP/FQDN': PORT
#hostpool = {
#               "10.10.10.100" : 8006,
#               "10.10.10.111" : 8006,
#               "pve1.example.com" : 8006
#           }
# This is the authentication backend that will be used to authenticate
#auth_backend = pve
# If enabled, 2FA TOTP entry dialog will show
#auth_totp = false
# If disabled, TLS certificate will not be checked
#tls_verify = false
# User name (if using token)
# NOTE: If only one cluster is defined, this will auto-login
#user = user
# API Token Name
#token_name = dvi
# API Token Value
#token_value = xxx-x-x-x-xxx
# Password Reset Command Launch. Has to be full executable Command
#pwresetcmd = start chrome --app=http://pwreset.example.com
# Automatically connect to a VMID upon authentication
#auto_vmid = 100


#[SpiceProxyRedirect]
# Proxmox API 返回的 SPICE 代理地址，有时需要改写主机名/端口
# 改写规则格式写法：`原IP:端口 = 替换后IP:端口`
# 1. 开启 inidebug 调试，查看当前返回的 proxy=pve1.example.com:3128
# 2. 把你实际的 PVE IP 填在等号右边，示例：123.123.123.123:6000
#pve1.example.com:3128 = 123.123.123.123:6000

[AdditionalParameters]

# 如果你需要自定义额外参数传给 virt-viewer，可以写在这个节点下
# 更多参数说明可查看官方文档：https://www.mankier.com/1/remote-viewer

#开启 USB 设备穿透
enable-usbredir = False
# 启用自动 USB 设备共享
enable-usb-autoshare = False
